comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
        branches:
          - devel
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true
        branches:
          - devel
ignore:
  - "R/plotting-functions.R"
  - "R/internal-msgs.R"
  - "R/exported-vars.R"
